# Parametros comunes a la aplicacion en ROS1
#


#general
user_height: 1.8
use_detection: true                         # if True, the detection mode is activated                 
use_planning: true                         # if True, the local planner mode is activated


#detection 
maximum_pcl_obstacles: 3                    # Maximum number of "detected" obstacles in the PointCloud to describe to the user  
detection_msg_period: 4                 # Time in seconds (NO ESTA SIENDO USADO AUN)

#Planning  
planning_msg_period: 2                             # Time in seconds (NO ESTA SIENDO USADO AUN)
