# Parametros para descarte de imagenes y equializacion del histograma
#

/**:
  ros__parameters:

    general:
      blur_filter: true                                     # if True, the images with blur are "removed"
      use_hist_equ: false                                    # if True, the input images are equalized
      left_image_topic: /zedm/zed_node/left/image_rect_color
      left_camera_info_topic: /zedm/zed_node/left/camera_info
      right_image_topic: /zedm/zed_node/right/image_rect_color
      right_camera_info_topic: /zedm/zed_node/right/camera_info

    imu_filter:
      max_angle: 46                                      # In degrees. The maximum angle difference / head inclination before the filter of images
      num_samples: 20                                            # The number of samples to use for the initial reference of the Imu / TF tree

    blur:
      kernel_size: 3                                      # Ther kernel size of the Sobel operator used by the Laplacian
      minZero: 100                                            # The decision threshold between non blur and blur image

        #hist_gpu:
            #backends:  'CUDA'                               # The VPI backend to use, which is CUDA by default (options: "CUDA", "XAVIER", "ORIN")
