global_frame: odom
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 1.0
#static_map: false
rolling_window: true
width: 7.0
height: 11.0

# Resolution is the same of the gmapping resolution
resolution: 0.12

obstacle_range: 5.0
raytrace_range: 5.5
#inflation_radius: 0.45
inflation_radius: 0.1
#cost_scaling_factor: 6.0
robot_radius: 0.35
#---standard pioneer footprint---

#---(in inches)---
#footprint: [ [10, -2], [7, -2], [7, -7], [-7.5, -7], [-10, 0], [-7.5, 7], [7, 7], [7, 2], [10, 2] ]

#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
#
#footprint: [[-0.40,-0.32],[-0.40,0.32], [0.50, 0.32], [0.50,-0.32]]
#footprint: [[-0.2,-0.20],[-0.20,0.20], [0.30, 0.20], [0.30,-0.20]]
#footprint: [[-0.25,-0.25],[-0.25,0.25], [0.35, 0.25], [0.35,-0.25]]
#footprint: [[-0.40,-0.30],[-0.40,0.50], [0.40, 0.30], [0.40,-0.50]]
transform_tolerance: 0.4
#map_type: costmap

observation_sources: points_scan_sensor

points_scan_sensor: {sensor_frame: disparity_frame, data_type: PointCloud2, topic: /points2, marking: true, clearing: true,
   max_obstacle_height: 0.3672, min_obstacle_height: -0.1088, obstacle_range: 5.0, raytrace_range: 5.5}

track_unknown_space: true
unknown_cost_value: -1



#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}



